//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAID_MVCWebApplication.SAID_ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SAIDGeneratorResponse", Namespace="http://schemas.datacontract.org/2004/07/SAID_RESTGeneratorService.App_Code")]
    [System.SerializableAttribute()]
    public partial class SAIDGeneratorResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAID_ServiceReference.ISAIDGeneratorService")]
    public interface ISAIDGeneratorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAIDGeneratorService/GenerateRandomSAIDNumber", ReplyAction="http://tempuri.org/ISAIDGeneratorService/GenerateRandomSAIDNumberResponse")]
        SAID_MVCWebApplication.SAID_ServiceReference.SAIDGeneratorResponse GenerateRandomSAIDNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISAIDGeneratorService/ValidateSAIDNumber", ReplyAction="http://tempuri.org/ISAIDGeneratorService/ValidateSAIDNumberResponse")]
        SAID_MVCWebApplication.SAID_ServiceReference.SAIDGeneratorResponse ValidateSAIDNumber(string IDNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISAIDGeneratorServiceChannel : SAID_MVCWebApplication.SAID_ServiceReference.ISAIDGeneratorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SAIDGeneratorServiceClient : System.ServiceModel.ClientBase<SAID_MVCWebApplication.SAID_ServiceReference.ISAIDGeneratorService>, SAID_MVCWebApplication.SAID_ServiceReference.ISAIDGeneratorService {
        
        public SAIDGeneratorServiceClient() {
        }
        
        public SAIDGeneratorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SAIDGeneratorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAIDGeneratorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SAIDGeneratorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SAID_MVCWebApplication.SAID_ServiceReference.SAIDGeneratorResponse GenerateRandomSAIDNumber() {
            return base.Channel.GenerateRandomSAIDNumber();
        }
        
        public SAID_MVCWebApplication.SAID_ServiceReference.SAIDGeneratorResponse ValidateSAIDNumber(string IDNumber) {
            return base.Channel.ValidateSAIDNumber(IDNumber);
        }
    }
}
